name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.1.1
  - pyyaml=6.0
  - hydra-core=1.3.1
  - pip=22.3.1
  - pip:
      - wandb==0.13.9
      - protobuf==3.20.*
      - hydra-joblib-launcher==1.1.2