name: rental-prices-ny
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.1.1
  - ipython=8.9.0
  - notebook=6.5.2
  - jupyterlab=3.6.1
  - hydra-core=1.0.6
  - cookiecutter=2.1.1
  - matplotlib=3.6.3
  - pandas=1.5.3
  - gitdb=4.0.10
  - pip=22.3.1
  - pip:
      - wandb==0.13.9
      - protobuf==3.20.*