name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - pandas=1.5.3
  - matplotlib=3.6.3
  - seaborn=0.12.2
  - scipy=1.10.0
  - ydata-profiling=4.0.0
  - pip:
    - wandb==0.13.9