name: test_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - mlflow=2.1.1
  - pandas=1.5.3
  - scikit-learn=1.2.1
  - numpy=1.23.5
  - scipy=1.9.3
  - pip:
    - wandb==0.13.9